debug: true

logging:
  level:
    org.springframework: DEBUG
    net.iponweb.disthene: DEBUG

graphene:
  writer:
    blacklist:
      'test':
        - '^xxx_sum.*\.system\..*'
    carbon:
      bind: "0.0.0.0"
      port: 2003
      rollups:
        - 60s:5356800s
    index:
      name: "metric"
      cluster:
        - "127.0.0.1"
      port: 9300
      index: "metric"
      type: "path"
      cache: false
      expire: 3600
      bulk:
        actions: 10000
        interval: 5
    store:
      cluster:
        - "127.0.0.1"
      port: 9042
      userName: 'cassandra'
      userPassword: 'cassandra'
      keyspace: 'metric'
      columnFamily: 'metric'
      maxConnections: 2048
      pool: 1
      readTimeout: 10
      connectTimeout: 10
      maxRequests: 128
      loadBalancingPolicyName: 'TokenDcAwareRoundRobinPolicy'
      protocolVersion: "V2"
    stats:
      interval: 60
      tenant: "test"
      hostname: "disthene-1a"
      log: true
server:
  port: 8081
