debug: true

logging:
  level:
    org.springframework: DEBUG
    com.graphene: DEBUG

graphene:
  writer:
    blacklist:
      'test':
        - '^xxx_sum.*\.system\..*'
    input:
      graphite:
        carbon:
          bind: "0.0.0.0"
          port: 2003
          rollup: 60
  #        route:
  #          host: 127.0.0.1
  #          port: 2003
      kafka:
        enabled: false
        bootstrapServer: "localhost:9092"
        consumerGroupId: "graphene-writer"
        pollIntervalMs: 5000
        maxPollRecords: 1000
        topics: "graphene-test-0,graphene-test-1"
        payloadFormat: "GraphiteMetric"
        valueDeserializerClass: "com.graphene.writer.input.kafka.deserializer.GraphiteDeserializer"
    store:
      key:
        handlers:
          logging-key-store-handler:
            tenant: none
            rotation:
              strategy: "timeBasedRotation"
              period: "1d"
            handler:
              type: "LoggingKeyStoreHandler"
          simple-key-store-handler:
            tenant: none
            rotation:
              strategy: "noOpRotation"
            handler:
              type: "SimpleKeyStoreHandler"
              property:
                clusterName: "metric"
                cluster: "127.0.0.1"
                port: 9200
                templateIndexPattern: "simple-key-path*"
                index: "simple-key-path"
                type: "path"
                bulk:
                  actions: 10000
                  interval: 500
          rotated-simple-key-store-handler:
            tenant: none
            rotation:
              strategy: "timeBasedRotation"
              period: "1w"
            handler:
              type: "SimpleKeyStoreHandler"
              property:
                clusterName: "metric"
                cluster: "127.0.0.1"
                port: 9200
                templateIndexPattern: "simple-key-path*"
                index: "simple-key-path"
                type: "path"
                bulk:
                  actions: 10000
                  interval: 500
          index-based-key-store-handler:
            tenant: none
            rotation:
              strategy: "timeBasedRotation"
              period: "1w"
            handler:
              type: "IndexBasedKeyStoreHandler"
              property:
                clusterName: "metric"
                cluster: "127.0.0.1"
                port: 9200
                templateIndexPattern: "index-based-key-path*"
                index: "index-based-key-path"
                type: "path"
                bulk:
                  actions: 10000
                  interval: 500
          tag-based-key-store-handler:
            tenant: none
            rotation:
              strategy: "timeBasedRotation"
              period: "1w"
            handler:
              type: "TagBasedKeyStoreHandler"
              property:
                clusterName: "metric"
                cluster: "127.0.0.1"
                port: 9200
                templateIndexPattern: "tag-based-key-path*"
                index: "tag-based-key-path"
                type: "path"
                bulk:
                  actions: 10000
                  interval: 500
      data:
        handlers:
          simple-data-store-handler:
            tenant: NONE
            ttl: 604800
            keyspace: "metric"
            columnFamily: "metric"
            bucketSize: 0
            handler:
              type: "SimpleDataStoreHandler"
              property:
                cluster: "127.0.0.1"
                port: 9042
                userName: "cassandra"
                userPassword: "cassandra"
                maxConnections: 2048
                readTimeout: 10
                connectTimeout: 10
                maxRequests: 128
                maxQueueSize: 4194304 # 4 * 1024 * 1024
                loadBalancingPolicyName: "TokenDcAwareRoundRobinPolicy"
                protocolVersion: "V4"
          offset-based-data-store-handler:
            tenant: NONE
            ttl: 604800
            keyspace: "metric_offset"
            columnFamily: "metric"
            bucketSize: 604800
            handler:
              type: "OffsetBasedDataStoreHandler"
              property:
                cluster: "127.0.0.1"
                port: 9042
                userName: "cassandra"
                userPassword: "cassandra"
                maxConnections: 2048
                readTimeout: 10
                connectTimeout: 10
                maxRequests: 128
                maxQueueSize: 4194304 # 4 * 1024 * 1024
                loadBalancingPolicyName: "TokenDcAwareRoundRobinPolicy"
                protocolVersion: "V4"
    stats:
      interval: 60
      tenant: "graphene"
      hostname: "localhost"
      log: true
server:
  port: 8081
