debug: true

logging:
  level:
    org.springframework: DEBUG
    net.iponweb.disthene: DEBUG

graphene:
  writer:
    blacklist:
      'test':
        - '^xxx_sum.*\.system\..*'
    input:
      graphite.carbon:
        bind: "0.0.0.0"
        port: 2003
        rollups:
          - 60s:5356800s
    store:
      key:
        rotation:
          strategy: "timeBasedRotation"
          period: "1d"
        handlers:
          logging-key-store-handler:
            enabled: true
            tenant: none
          simple-key-store-handler:
            enabled: true
            tenant: none
            clusterName: "metric"
            cluster:
              - "127.0.0.1"
            port: 9300
            template-index-pattern: "simple-key-path*"
            index: "simple-key-path"
            type: "path"
            bulk:
              actions: 10000
              interval: 5
          index-based-key-store-handler:
            enabled: true
            tenant: none
            clusterName: "metric"
            cluster:
              - "127.0.0.1"
            port: 9300
            template-index-pattern: "index-based-key-path*"
            index: "index-based-key-path"
            type: "path"
            bulk:
              actions: 10000
              interval: 5
      data:
        rollup: 60s
        retention: 30d
        handlers:
          cassandra:
            cluster:
              - "127.0.0.1"
            port: 9042
            userName: 'cassandra'
            userPassword: 'cassandra'
            keyspace: 'metric'
            columnFamily: 'metric'
            maxConnections: 2048
            pool: 1
            readTimeout: 10
            connectTimeout: 10
            maxRequests: 128
            loadBalancingPolicyName: 'TokenDcAwareRoundRobinPolicy'
            protocolVersion: "V2"
    stats:
      interval: 60
      tenant: "graphene"
      hostname: "localhost"
      log: true
server:
  port: 8081
