version: '3'

services:
  cassandra:
    image: launcher.gcr.io/google/cassandra2
    ports:
      - 7000:7000
      - 7199:7199
      - 9042:9042
      - 9160:9160
    environment:
      CASSANDRA_CLUSTER_NAME: metric
    container_name: cassandra
  elasticsearch:
    image: elasticsearch:6.8.3
    volumes:
      - ./infra/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: "single-node"
    container_name: elasticsearch
  cerebro:
    image: lmenezes/cerebro:0.8.3
    ports:
      - 9000:9000
    container_name: cerebro
  grafana:
    image: grafana/grafana:6.3.5
    ports:
      - 80:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    container_name: grafana
