version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  cassandra:
    image: launcher.gcr.io/google/cassandra2
    ports:
      - 7000:7000
      - 7199:7199
      - 9042:9042
      - 9160:9160
    volumes:
      - ./.docker/cassandra:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: metric
    container_name: cassandra
  elasticsearch:
    image: elasticsearch:6.7.1
    volumes:
      - ./infra/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: "single-node"
    container_name: elasticsearch
  cerebro:
    image: lmenezes/cerebro:0.8.3
    ports:
      - 9000:9000
    container_name: cerebro
  grafana:
    image: grafana/grafana:6.3.5
    ports:
      - 80:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    container_name: grafana
