apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphene-reader.fullname" . }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "graphene-reader.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" | trunc 63 }}
    helm.sh/chart: {{ include "graphene-reader.chart" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: {{ include "graphene-reader.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
