# Default values for graphene-writer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: dark0096/graphene-writer
  tag: 1.3.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

HeapOptions: "-Xmx1G -Xms1G"

# livenessProbe:
#   tcpSocket:
#     port: writer
#   initialDelaySeconds: 60
#   timeoutSeconds: 30
#   failureThreshold: 10

# readinessProbe:
#   tcpSockethttpGet:
#     port: writer
    
service:
  type: LoadBalancer
  port: 2003
  annotations: {}
    # external-dns.alpha.kubernetes.io/hostname=chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# ------------------------------------------------------------------------------
# Carbon:
# ------------------------------------------------------------------------------

carbon:
  # binding to environment variable of GRAPHENE_CARBON_HOST 
  host: ""
  

# ------------------------------------------------------------------------------
# Cassandra:
# ------------------------------------------------------------------------------

cassandra:
  cluster:
    # binding to environment variable of GRAPHENE_DATA_CASSANDRA_CLUSTER 
    endpoint: ""

# ------------------------------------------------------------------------------
# Elasticsearch:
# ------------------------------------------------------------------------------

elasticsearch:
  cluster:
    # binding to environment variable of GRAPHENE_INDEX_ELASTICSEARCH_CLUSTER 
    endpoint: ""
