version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-stretch
    steps:
      - checkout
      - run:
          name: "Run test"
          command: |
            ./gradlew ktlint test --info
