version: '3'

services:
  graphene-writer:
    image: dark0096/graphene-writer:1.2.0
    environment:
      GRAPHENE_DATA_CASSANDRA_CLUSTER: 'cassandra'
      GRAPHENE_INDEX_ELASTICSEARCH_CLUSTER: 'elasticsearch'
      GRAPHENE_CARBON_HOST: 'graphene-writer'
      GRAPHENE_HEAP_OPTS: '-Xmx1G -Xms1G'
    ports:
      - 2003:2003
    container_name: graphene-writer
